# Generated by Django 2.1.7 on 2019-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aadhar_Number', models.IntegerField(default=0)),
                ('DOB', models.DateField()),
                ('Religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Others', 'Others')], max_length=10)),
                ('Address', models.CharField(max_length=50)),
                ('Annual_income', models.IntegerField(default=0)),
                ('Occupation', models.CharField(max_length=20)),
            ],
        ),
    ]
