# Generated by Django 2.1.7 on 2019-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Child_Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Group', models.CharField(choices=[('Between 2 to 5', 'Between 2 to 5'), ('Between 5 to 10', 'Between 5 to 10'), ('Between 10 to 15', 'Between 10 to 15'), ('Between 15 to 20', 'Between 15 to 20')], max_length=30)),
                ('Religion', models.CharField(max_length=30)),
            ],
        ),
    ]
