# Generated by Django 2.1.7 on 2019-10-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='Name',
        ),
    ]
